apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: externalsecret-sample
spec:
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore

  target:
    name: secret-to-be-created
    creationPolicy: Owner

  refreshInterval: 1h

  data:
  - secretKey: secret-key-to-be-managed
    remoteRef:
      key: mysecret
      version: latest
  dataFrom:
  - remoteRef:
    key: remote-key-in-the-provider
